### ISSUE TITLE
Error importing it into application

### ISSUE THREAD

**Issue by Yana13** [Lightstreamer/Lightstreamer-lib-client-javascript#2]
Hi,
I have an issue when trying to use lightstreamer-client-web in my React application. When trying to import it into .ts file I get the following error: 
"Trying to load a browser-only module on non-browser environment"
On RunKit example of the package I see the same error ( https://npm.runkit.com/lightstreamer-client-web ). Why is this happening and why can't I import the library into my front-end application code?

**Comment by ghost** [comment]
Hello,

As far as I understand, RunKit runs the code in a Node.js environment.  If you need a Lightstreamer client for Node.js, please use the library [lightstreamer-client-node](https://www.npmjs.com/package/lightstreamer-client-node).

I confirm that Lightstreamer supports React framework. Please refer to the demos [StockList-client-reactnative](https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-reactnative) and [StockList-client-react](https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-react) for more details.

**Comment by Yana13** [comment]
Okay, thanks. As it turns out my code was running on node.js as well as RunKit.
Thanks!
