### ISSUE TITLE
ESM build should not include promise polyfill

### ISSUE THREAD

**Issue by bryanforbes** [Lightstreamer/Lightstreamer-lib-client-javascript#3]
All browsers that support including ES modules via a script tag have promises implemented:

https://caniuse.com/promises
https://caniuse.com/es6-module

Because the polyfill cannot be shaken out by webpack, including it in the published ESM build increases the size of projects including `lightstreamer-web-client` (most of which either don't need a polyfill or include their own already).

**Comment by ghost** [comment]
Hello,

To shrink the size of the library you can comment out the polyfill line in the file _tools/build.config.js_ and rebuild the library. 
For example, to rebuild the ES library only, enter the directory _tools_ and run the command _node build.js -f esm_.
See the section [Building](https://github.com/Lightstreamer/Lightstreamer-lib-client-javascript#building) for further information.

**Comment by bryanforbes** [comment]
I'm already building my application using `angular-cli`. Adding another step to an already complex application build process (which includes Jenkins and various deploy steps) to remove an unnecessary polyfill isn't a usable solution for developers. Please reconsider.

**Comment by AlessandroAlinone** [comment]
Bryan, sorry for the very late response. We are actually reconsidering the issue. But it looks like removing promise polyfill would reduce the library size just by 1.6% before minification. That's why we didn't take this route. Thoughts?
Thanks
